CodeHouse/Controllers/AdminController.cs
using CodeHouse.Data;
using ProjectHouse.Models.Article;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CodeHouse.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        public UserContext DbContext;
        public AdminController(UserContext DbContext)
        {
            this.DbContext = DbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult EditArticle(int id)
        {
            ViewBag.Categories = DbContext.Categories.ToArray();
            return View(DbContext.Articles.Single(a => a.Id == id));
        }
        [HttpPost]
        public IActionResult EditArticle(Article model)
        {
            DbContext.Articles.Update(model);
            DbContext.SaveChanges();
           return RedirectToAction("Index");
        }
        public IActionResult AddArticle()
        {
            ViewBag.Categories = DbContext.Categories.ToArray();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddArticle(Article model)
        {
            DbContext.Articles.Add(model);
            await DbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public IActionResult DeleteArticle()
        {
            return View();
        }
        public IActionResult AddCategory()
        {
            ViewBag.Categories = DbContext.Categories.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult AddCategory(Category model)
        {
            DbContext.Add(model);
            DbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditCategory(int id)
        {
            ViewBag.Categories = DbContext.Categories.ToList();
            return View(DbContext.Categories.Single(c => c.Id == id));
        }
        [HttpPost]
        public IActionResult EditCategory(Category model)
        {
            DbContext.Categories.Update(model);
            DbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult DeleteCategory(int id)
        {
            
            return View(DbContext.Categories.Single(c => c.Id == id));
        }
        [HttpPost]
        public IActionResult DeleteCategory(Category model)
        {
            DbContext.Categories.Remove(model);
            DbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CodeHouse/Controllers/ArticleController.cs
using CodeHouse.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectHouse.Models.Article;
using ProjectHouse.ViewModels.Article;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodeHouse.Controllers
{

    public class ArticleController : Controller
    {

        public UserContext dbContext;
        public ArticleController(UserContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult Index() => View(dbContext.Articles.OrderByDescending(n => n.Id));
        
        public IActionResult Read(int id)
        {
            ViewBag.ArtcilePartials = dbContext.ArticlePartials.Where(x => x.ArticleId == id).ToList();
            return View(dbContext.Articles.FirstOrDefault(p => p.Id == id));
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            //var model = dbContext.Articles.FirstOrDefault(c => c.Id == id);
            //Article model = dbContext.Articles.Include(x => x.ArticleCategories).ThenInclude(x => x.Category).FirstOrDefault(a=>a.Id == id);

            ArticleViewModel newModel = new ArticleViewModel();

            newModel.Article = dbContext.Articles.Include(x => x.ArticleCategories).ThenInclude(x => x.Category).FirstOrDefault(a => a.Id == id);
            newModel.ArticlePartial = dbContext.ArticlePartials.Where(x => x.ArticleId == id).ToList();

            AssignedCategoryData(newModel.Article);

            return View(newModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(
            int id,
            ArticleViewModel articleViewModel,
            string[] selectedCategories,
            string returnUrl,
            string[] partialTitle,
            string[] partialContent,
            string[] newPartialTitle,
            string[] newPartialContent,
            int[] deletePartialArticle)
        {
            articleViewModel.Article = await dbContext.Articles.Include(x => x.ArticleCategories).ThenInclude(x => x.Category).FirstOrDefaultAsync(c => c.Id == id);

            await TryUpdateModelAsync<ArticleViewModel>(articleViewModel);
            UpdateArticleCategories(selectedCategories, articleViewModel.Article);
            UpdatePartialContent(id, partialTitle, partialContent, articleViewModel);

            try
            {
                await dbContext.SaveChangesAsync();
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes!");
            }

            if (newPartialTitle != null && newPartialContent != null)
            { AddNewPartialPage(id, newPartialTitle, newPartialContent); }
            if (deletePartialArticle != null)
            { DeletePartialContent(id, deletePartialArticle); }

            if (!string.IsNullOrEmpty(returnUrl)) { return LocalRedirect(returnUrl); }
            return RedirectToAction("Index");
        }

        public void AddNewPartialPage(int id, string[] title, string[] content)
        {
            List<ArticlePartial> model = new List<ArticlePartial>();
            for (int i = 0; i < title.Length; i++)
            { model.Add(new ArticlePartial { Title = title[i], ContentText = content[i], ArticleId = id }); }
            dbContext.AddRange(model);
            dbContext.SaveChanges();
        }

        public void DeletePartialContent(int id, int[] deleteIds)
        {
            List<ArticlePartial> modelList = dbContext.ArticlePartials.Where(x => x.ArticleId == id).ToList();
            List<ArticlePartial> modelToDelete = new List<ArticlePartial>();
            for (int i = 0; i < deleteIds.Length; i++)
            {
                var rm = modelList.Find(x => x.Id == deleteIds[i]);
                modelToDelete.Add(rm);
            }
            dbContext.RemoveRange(modelToDelete);
            dbContext.SaveChanges();
        }

        public void UpdatePartialContent(int id, string[] title, string[] content, ArticleViewModel model)
        {

            model.ArticlePartial = dbContext.ArticlePartials.Where(x => x.ArticleId == id).ToList();
            int i = 0;
            foreach (var item in model.ArticlePartial)
            {
                model.ArticlePartial[i].Title = title[i];
                model.ArticlePartial[i].ContentText = content[i];
                i++;
            }
        }

        public void AssignedCategoryData(Article model)
        {
            var allCategories = dbContext.Categories;
            var articleCategories = new HashSet<int>(model.ArticleCategories.Select(c => c.CategoryId));
            var viewModel = new List<CategorySortData>();
            foreach (var category in allCategories)
            {
                viewModel.Add(new CategorySortData
                {
                    CategoryId = category.Id,
                    CategoryName = category.Name,
                    ParentCategoryId = category.ParentId,
                    IsAssigned = articleCategories.Contains(category.Id)
                });
            }
            ViewData["Categories"] = viewModel;
        }

        public void UpdateArticleCategories(string[] selectedCategories, Article model)
        {
            if (selectedCategories == null)
            {
            }
            var selectedCategoriesHS = new HashSet<string>(selectedCategories);
            var articleCategoriesHS = new HashSet<int>(model.ArticleCategories.Select(c => c.Category.Id));
            foreach (var category in dbContext.Categories)
            {
                if (selectedCategoriesHS.Contains(category.Id.ToString()))
                {
                    if (!articleCategoriesHS.Contains(category.Id))
                    {
                        model.ArticleCategories.Add(new ArticleCategory { ArticleId = model.Id, CategoryId = category.Id });
                    }
                }
                else
                {
                    if (articleCategoriesHS.Contains(category.Id))
                    {
                        ArticleCategory categoryToRemove = model.ArticleCategories.FirstOrDefault(c => c.CategoryId == category.Id);
                        dbContext.Remove(categoryToRemove);
                    }
                }
            }
        }
    }
}

CodeHouse/Views/Admin/AddArticle.cshtml
@model Article
@{
    //var tryCategories = ViewBag.Categories as IEnumerable<ArticleCategoryModel>;
}


<form asp-action="AddArticle" asp-controller="Admin">
    <div class="form-group">
        <label asp-for="Title" class="control-label"><b>Title</b></label>
        <input type="text" asp-for="Title" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="ShortText" class="control-label"><b>Short Text</b></label>
        <textarea rows="10" placeholder="Введите сообщение" type="text" asp-for="ShortText" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="Text" class="control-label"><b>Main text</b></label>
        <textarea rows="10" placeholder="Введите сообщение" type="text" asp-for="Text" class="form-control"></textarea>
    </div>

@*    <select asp-for="CategoryId">
        <option>Select category</option>
        @foreach (var item in ViewBag.Categories)
        {
            <option value="@item.Id">@item.Name</option>
        }
    </select>*@

    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>



<xmp>
<xmp>
<div class="alert alert-success" role="alert">
<b>[C# CODE]</b><hr><pre>
                code
</pre>
</div>
</xmp>
</xmp>

CodeHouse/Views/Admin/AddCategory.cshtml
@model Category
@{ 
    var categories = ViewBag.Categories as IEnumerable<Category>;
}

<form asp-action="AddCategory" asp-controller="Admin">
    <div class="form-group">
        <label asp-for="Name" class="control-label"><b>Title</b></label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"><b>Short Text</b></label>
        <textarea rows="10" placeholder="Введите сообщение" type="text" asp-for="Description" class="form-control"></textarea>
    </div>

@*    <select asp-for="ParentCategoryId">
        <option value="null">No parent category</option>
        @foreach (var categoryList in categories)
        {
            @if (categoryList.ParentCategoryId == null)
            {<option value="@categoryList.Id">@categoryList.Name</option>}
        }
    </select>*@
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

CodeHouse/Views/Admin/DeleteCategory.cshtml
@model Category

<form asp-action="DeleteCategory" asp-controller="Admin">
    <h2>Вы точно хотите удалить категорию @Model.Name ?</h2>
    <div class="form-group">
        <input type="submit" value="Да удалить категорию!" class="btn btn-default" />
    </div>
</form>

CodeHouse/Views/Admin/EditArticle.cshtml
@model Article

<form asp-action="EditArticle" asp-controller="Admin">
    <div class="form-group">
        <label asp-for="Title" class="control-label"><b>Title</b></label>
        <input type="text" asp-for="Title" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="ShortText" class="control-label"><b>Short Text</b></label>
        <textarea rows="10" placeholder="Введите сообщение" type="text" asp-for="ShortText" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="Text" class="control-label"><b>Main text</b></label>
        <textarea rows="10" placeholder="Введите сообщение" type="text" asp-for="Text" class="form-control"></textarea>
    </div>

@*    <select asp-for="CategoryId">
        <option>Select category</option>
        @foreach (var item in ViewBag.Categories)
        {
            @if (item.ParentCategoryId != null) {<option value="@item.Id">@item.Name</option>}
        }
    </select>*@

    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

<xmp>
<xmp>
<div class="alert alert-success" role="alert">
<b>[C# CODE]</b><hr><pre>
code
</pre>
</div>
</xmp>
</xmp>

CodeHouse/Views/Admin/EditCategory.cshtml
@model Category
@{
    var categories = ViewBag.Categories as IEnumerable<Category>;
}

<form asp-action="EditCategory" asp-controller="Admin">
    <div class="form-group">
        <label asp-for="Name" class="control-label"><b>Title</b></label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"><b>Short Text</b></label>
        <textarea rows="10" placeholder="Введите сообщение" type="text" asp-for="Description" class="form-control"></textarea>
    </div>

@*    <select asp-for="ParentCategoryId">
        <option value="null">No parent category</option>
        @foreach (var categoryList in categories)
        {
            @if (categoryList.ParentCategoryId == null)
            {
                <option value="@categoryList.Id">@categoryList.Name</option>
}
        }
    </select>*@
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

CodeHouse/Views/Admin/Index.cshtml
<h1>Admin</h1>

<a asp-controller="Admin" asp-action="AddArticle">Add article</a>
<a asp-controller="Admin" asp-action="AddCategory">Add category</a>
<a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Articles</a>