CodeHouse/Controllers/AdminController.cs
using CodeHouse.Data;
using ProjectHouse.Models.Article;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CodeHouse.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        public UserContext DbContext;
        public AdminController(UserContext DbContext)
        {
            this.DbContext = DbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult EditArticle(int id)
        {
            ViewBag.Categories = DbContext.Categories.ToArray();
            return View(DbContext.Articles.Single(a => a.Id == id));
        }
        [HttpPost]
        public IActionResult EditArticle(Article model)
        {
            DbContext.Articles.Update(model);
            DbContext.SaveChanges();
           return RedirectToAction("Index");
        }
        public IActionResult AddArticle()
        {
            ViewBag.Categories = DbContext.Categories.ToArray();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddArticle(Article model)
        {
            DbContext.Articles.Add(model);
            await DbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public IActionResult DeleteArticle()
        {
            return View();
        }
        public IActionResult AddCategory()
        {
            ViewBag.Categories = DbContext.Categories.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult AddCategory(Category model)
        {
            DbContext.Add(model);
            DbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditCategory(int id)
        {
            ViewBag.Categories = DbContext.Categories.ToList();
            return View(DbContext.Categories.Single(c => c.Id == id));
        }
        [HttpPost]
        public IActionResult EditCategory(Category model)
        {
            DbContext.Categories.Update(model);
            DbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult DeleteCategory(int id)
        {
            
            return View(DbContext.Categories.Single(c => c.Id == id));
        }
        [HttpPost]
        public IActionResult DeleteCategory(Category model)
        {
            DbContext.Categories.Remove(model);
            DbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CodeHouse/Controllers/CategoryController.cs
using CodeHouse.Data;
using ProjectHouse.Models.Article;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace ProjectHouse.Controllers
{
    public class CategoryController : Controller
    {
        public UserContext dbContext { get; set; }
        public CategoryController(UserContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Categories()
        {
            return View(dbContext.Categories.ToList());
        }
        [HttpGet]
        public IActionResult Category(int? id)
        {
            var model = dbContext.Articles.Include(c=>c.ArticleCategories).Where(c=>c.ArticleCategories.Any(b=>b.CategoryId == id)).ToList();
            ViewBag.CategoryId = dbContext.Categories.FirstOrDefault(x => x.Id == id).Id;
            ViewBag.CategoryName = dbContext.Categories.FirstOrDefault(x => x.Id == id).Name;
            return View(model);
        }
        [HttpGet]
        public IActionResult AddEdit(int? id)
        {
            var model = dbContext.Categories.FirstOrDefault(x=>x.Id == id);
            ViewBag.Categories = dbContext.Categories.ToList();
            return View(model);
        }
        [HttpPost]
        public IActionResult AddEdit(Category model, string returnUrl)
        {
            dbContext.Update(model);
            dbContext.SaveChanges();
            if (!string.IsNullOrEmpty(returnUrl)) { return LocalRedirect(returnUrl); }
            return RedirectToAction("Categories");
        }
    }
}

CodeHouse/Controllers/LearningController.cs
using CodeHouse.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectHouse.Models.Learning;
using System;
using System.Linq;

namespace ProjectHouse.Controllers
{

    public class LearningController : Controller
    {
        private readonly UserContext dbContext;

        public LearningController(UserContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult Index()
        {
            ViewBag.HomeWorks = dbContext.HomeWorks.ToList();
            return View(dbContext.Groupes.ToList().OrderByDescending(o => o.Position));
        }
        [HttpGet]
        public IActionResult AddEditGroupe(int? id)
        {
            if (id == null) { return View(); }
            return View(dbContext.Groupes.FirstOrDefault(g => g.Id == id));
        }
        [HttpPost]
        public IActionResult AddEditGroupe(Groupe model, string returnUrl)
        {
            if (model.Id == 0)
            {
                model.Date = DateTime.Now;
                model.Position = 0;
                model.Status = GroupeStatus.NotCompleted;
                dbContext.Groupes.Add(model);
            }
            else
            {
                dbContext.Groupes.Update(model);
            }
            dbContext.SaveChanges();
            if (!String.IsNullOrEmpty(returnUrl)) { return LocalRedirect(returnUrl); }
            return RedirectToAction("Index");
        }
        public IActionResult HomeWorkByGroupe(int? id)
        {
            if (id == null) { return RedirectToAction("Index"); }
            ViewBag.GroupName = dbContext.Groupes.FirstOrDefault(i=>i.Id == id).Name;
            return View(dbContext.HomeWorks.ToList().Where(g => g.GroupeId == id).OrderBy(s => s.Status).ThenByDescending(p=>p.Position));
        }
        [HttpGet]
        public IActionResult HomeWork(int id) => View(dbContext.HomeWorks.FirstOrDefault(i=>i.Id == id));
        [HttpGet]
        public IActionResult AddEditHomeWork(int id)
        {
            ViewBag.Groupes = new SelectList(dbContext.Groupes.ToList(), "Id", "Name").OrderByDescending(i => i.Value);
            return View(dbContext.HomeWorks.FirstOrDefault(i => i.Id == id));
        }
        [HttpPost]
        public IActionResult AddEditHomeWork(HomeWork model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                dbContext.HomeWorks.Update(model);
            }
            else
            {
                model.Date = DateTime.Now;
                model.Status = HomeWorkStatus.NotStarted;
                dbContext.HomeWorks.Add(model);
            }
            dbContext.SaveChanges();
            if (!String.IsNullOrEmpty(returnUrl)) { return LocalRedirect(returnUrl); }
            return RedirectToAction("Index");
        }
    }
}

CodeHouse/Controllers/ProjectController.cs
using CodeHouse.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectHouse.Models.Project;
using System.Linq;
using System;
using ProjectHouse.ViewModels.Project;

namespace ProjectHouse.Controllers
{

    public class ProjectController : Controller
    {
        protected readonly UserContext dbContext;

        public ProjectController(UserContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult Index()
        {
            ProjectListViewModel model = new ProjectListViewModel();
            model.Projects = dbContext.Projects.OrderByDescending(x => x.Position);
            model.Tasks = dbContext.ProjectsTasks.Where(x => x.TaskStatus != TaskStatus.Completed);
            return View(model);
        }

        [HttpGet]
        public IActionResult AddEditProject(int? id)
        {
            if (id == null) { return View(); }
            return View(dbContext.Projects.FirstOrDefault(p => p.Id == id));
        }
        [HttpPost]
        public IActionResult AddEditProject(Project model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                dbContext.Projects.Update(model);
            }
            else
            {
                dbContext.Projects.Add(model);
            }
            dbContext.SaveChanges();

            if (!string.IsNullOrEmpty(returnUrl)) { return LocalRedirect(returnUrl); }
            return View(model);
        }
        [HttpGet]
        public IActionResult AddEditTask(int? id, int? id2, int id3)
        {
            if (id == null || id == 0 && id2 == null) { return Content("You miss some details!"); }

            if (id == 0)
            {
                Task task = new Task() { ProjectId = id2.Value, CategoryId = id3 };
                return View(task);
            }

            var model = dbContext.ProjectsTasks.Where(x => x.Id == id).FirstOrDefault();

            if (model != null) { return View(model); }

            return Content("Model is null");
        }
        [HttpPost]
        public IActionResult AddEditTask(Task model, string returnUrl)
        {
            if (ModelState.IsValid && model.Id != 0)
            {
                dbContext.ProjectsTasks.Update(model);
            }
            else
            {
                model.TaskImportance = TaskImportance.Normal;
                model.TaskStatus = TaskStatus.InActive;
                model.Date = DateTime.Now;
                dbContext.ProjectsTasks.Add(model);
            }
            dbContext.SaveChanges();

            if (!string.IsNullOrEmpty(returnUrl)) { return LocalRedirect(returnUrl); }
            return View(model);
        }
        [HttpGet]
        public IActionResult AddEditTaskCategory(int? id, int? id2)
        {
            if (id == null || id == 0)
            {
                TaskCategory model = new TaskCategory() { ProjectId = id2.Value };
                return View(model);
            }
            return View(dbContext.ProjectsTasksCategories.Where(x => x.Id == id).FirstOrDefault());
        }
        [HttpPost]
        public IActionResult AddEditTaskCategory(TaskCategory model, string returnUrl)
        {
            if (ModelState.IsValid && model.Id != 0)
            { dbContext.ProjectsTasksCategories.Update(model); }
            else { dbContext.ProjectsTasksCategories.Add(model); }
            dbContext.SaveChanges();
            if (!string.IsNullOrEmpty(returnUrl)) { return LocalRedirect(returnUrl); }
            return View(model);
        }

        public IActionResult ProjectMain(int id)
        {
            ProjectMainViewModel projectMainViewModel = new ProjectMainViewModel();
            projectMainViewModel.ProjectTaskList = dbContext.ProjectsTasks.Where(x => x.ProjectId == id).OrderBy(x => x.TaskStatus).ThenBy(x => x.TaskImportance).ThenByDescending(x => x.Position).ToList();
            projectMainViewModel.ProjectArticleList = dbContext.ProjectArticles.Where(x=>x.ProjectId == id).ToList();
            projectMainViewModel.Project = dbContext.Projects.FirstOrDefault(x => x.Id == id);
            return View(projectMainViewModel);
        }

        public IActionResult TaskCategory(int id)
        {
            ViewBag.ProjectName = dbContext.Projects.Where(x => x.Id == id).FirstOrDefault()?.Name;
            ViewBag.ProjectId = dbContext.Projects.Where(x => x.Id == id).FirstOrDefault()?.Id;
            return View(dbContext.ProjectsTasksCategories.Where(x => x.ProjectId == id).OrderByDescending(x => x.Position).ToList());
        }
        public IActionResult TaskList(int id)
        {
            var model = dbContext.ProjectsTasksCategories.Where(x => x.Id == id).FirstOrDefault();
            ViewBag.ProjectName = dbContext.Projects.Where(x => x.Id == model.ProjectId).FirstOrDefault()?.Name;
            int projectID = dbContext.Projects.Where(x => x.Id == model.ProjectId).FirstOrDefault().Id;
            ViewBag.ProjectId = projectID;
            ViewBag.CategoryId = id;
            ViewBag.CategoryName = dbContext.ProjectsTasksCategories.Where(x => x.Id == id).FirstOrDefault().Name;

            return View(dbContext.ProjectsTasks
                .Where(x => x.CategoryId == id)
                .OrderBy(x => x.TaskStatus)
                .ThenByDescending(x => x.Position)
                .ThenBy(x => x.TaskImportance)
                .ToList());
        }
        public IActionResult TaskView(int id)
        {
            var model = dbContext.ProjectsTasks.Where(x => x.Id == id).FirstOrDefault();
            ViewBag.ProjectName = dbContext.Projects.Where(x => x.Id == model.ProjectId).FirstOrDefault()?.Name;
            ViewBag.ProjectId = dbContext.Projects.Where(x => x.Id == model.ProjectId).FirstOrDefault()?.Id;
            ViewBag.CategoryName = dbContext.ProjectsTasksCategories.Where(x => x.Id == model.CategoryId).FirstOrDefault()?.Name;
            ViewBag.CategoryId = dbContext.ProjectsTasksCategories.Where(x => x.Id == model.CategoryId).FirstOrDefault()?.Id;
            return View(model);
        }
        [HttpGet]
        public IActionResult Article(int id)
        {
           var model = dbContext.ProjectArticles.FirstOrDefault(x => x.Id == id);
           ViewBag.Project = dbContext.Projects.Where(x => x.Id == model.ProjectId).FirstOrDefault();
           return View(model);
        }
        [HttpGet]
        public IActionResult AddEditArticle(int id, int id2)
        {
            if (id2 <= 0) { return RedirectToAction("Index"); }

            if (id > 0) { return View(dbContext.ProjectArticles.FirstOrDefault(x => x.Id == id)); }
            else { ProjectArticle projectArticle = new ProjectArticle() { ProjectId = id2 }; return View(projectArticle); }
        }
        [HttpPost]
        public IActionResult AddEditArticle(ProjectArticle model, string returnUrl)
        {
            if (model.Id > 0) { dbContext.Update(model); }
            else { dbContext.Add(model); }
            dbContext.SaveChanges();

            if(!String.IsNullOrEmpty(returnUrl)) { return LocalRedirect(returnUrl); }
            else { return View(model); }
        }
    }
}

CodeHouse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project House</title>

    @*   <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project House</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Learning" asp-action="Index">HomeWork</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyTime" asp-action="Index">MyTime</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Categories">Categories</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">@User.Identity.Name</a></li>
                            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">LOGOUT</a></li>
                            @if (User.IsInRole("admin"))
                            {
                                <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="index">Admin Zone</a></li>
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CodeHouse - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*    <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>*@
    @*    @await RenderSectionAsync("Scripts", required: false)*@
</body>
</html>